### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by sl33t** [audiolion/WebII-Group-Project#10]
We need to implement the forum and discuss how. Do we want nested comments, email notification for comments, markdown posts, and other details.

**Comment by audiolion** [comment]
I think simplest way to go is your basic mass forum with a search or tags for lessons. We gotta see what django packages are out there and from there see what is possible.

**Comment by sl33t** [comment]
Still needs styling but everything works on the backend

**Comment by sl33t** [comment]
Forum finished just need post styling

**Comment by audiolion** [comment]
if possible we should try to include a name/timestamp on the messages posted by users in response

**Comment by sl33t** [comment]
Post page has rough styling finished. 3c8936d
