### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by sl33t** [audiolion/WebII-Group-Project#12]
Do we want a contact page with a little form like email us or to add that to a meet the team page or scrap it all together.

**Comment by audiolion** [comment]
I think contact is probably important. Separate page but relegated to footer and a form that sends an email so we dont reveal our email to crawlers

**Comment by sl33t** [comment]
Hiding the email is a smart idea so we dont have to do trickery to hide it just have the form and maybe a capcha.

**Comment by sl33t** [comment]
Scrapped in favor of social media
