### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by sl33t** [audiolion/WebII-Group-Project#13]
Do we want to do a little description of the project on this page? What should it say. I envision it similar to the about page we are required on our individual sites where we discuss how it was built and point people to important features.

**Comment by audiolion** [comment]
Yeah we can also ask prof tmr what he thinks, if it goes out of character to discuss tech used to build site etc.

**Comment by sl33t** [comment]
Sounds good.

**Comment by sl33t** [comment]
Merged into meet the team/ discontinued
