### ISSUE TITLE
Redesign FAQ and Quick reference pages

### ISSUE THREAD

**Issue by sl33t** [audiolion/WebII-Group-Project#14]
These pages are in a major need of a redesign but we are gonna wait until Natasha is present to do that. We are currently thinking perhaps box each part and give it like a patterned kinda look.

**Comment by audiolion** [comment]
Check out the new commits I made and see what you think

acdcf98db2342ad2b05a964995b9247e12660c14

**Comment by sl33t** [comment]
Looks much cleaner right now. We need to rethink that local nav maybe use the same kind we have in lessons to give it a cohesive look.

**Comment by audiolion** [comment]
Yeah for sure. Cohesiveness between navs. Honestly we could use the blackish color for those material box wells instead of gray if we wanted to and put the teal text in there.

**Comment by sl33t** [comment]
Quick Reference finished Faq needs same revamp

**Comment by JTrowse89** [comment]
This was updated over the course of a few meetings. Boxes were added to separate content and changes were made so that formatting and break points were all correct.
