### ISSUE TITLE
badges update model to include text field

### ISSUE THREAD

**Issue by audiolion** [audiolion/WebII-Group-Project#22]
should update the model of badges to have a text field describing the badge, otherwise there is no association with what the badge was earned for.

Example finishing lesson 1 should get you the "Tenderfoot", lesson 2, "Beginner", "Irregular" ... "Guru/Sensei/Veteran" ... "Regex Disciple"

I say we choose a theme of hierarchy and just run down the list:

Follower
Acolyte
Disciple
Priest

Gennin
Chunin
Jonin
Kekkei Genkai
...
Sannin

does anyone have some favorite show or something we could base it off of

**Comment by sl33t** [comment]
Josh is added the names now but it works
