### ISSUE TITLE
Meet the Team Page

### ISSUE THREAD

**Issue by JustinHaddock** [audiolion/WebII-Group-Project#24]
Assets for meet the team page from Natasha

**Comment by audiolion** [comment]
Lol llama

**Comment by mistrymayhem** [comment]
Ah sorry about that haha friend of mine was logged in on my computer and I forgot to log him out before making this !

**Comment by sl33t** [comment]
Where are these assets stored?

**Comment by mistrymayhem** [comment]
Just emailed them to you, also should be on the google drive

**Comment by JustinHaddock** [comment]
Hey guys, i'm not in your group. Can I get out of the email chains?

**Comment by sl33t** [comment]
Sorry for bothering you JustinI am closing the issue. It is finished and going online now
