### ISSUE TITLE
Home page after login

### ISSUE THREAD

**Issue by audiolion** [audiolion/WebII-Group-Project#6]
Should the home page after login always redirect to the user dashboard?

Currently they can get back to the page that says "Learn More" // "Sign Up". We have an if statement that says if they are not authenticated to include the "Sign Up" button, so it disappears if they are logged in and just shows "Learn More" by itself and it looks pretty weird.

[how it looks](http://i.imgur.com/3sv6h53.png)

Partly this is because it is not centered, it is still retaining the margin and padding as if the other button was there. So we could fix that to have it centered and it would look more natural.

However, I wonder if that page should even be shown if they are already authenticated, if it should just always redirect to the dashboard. It seems like other websites do this, they show you the default landing/sign up page if you aren't authenticated when you visit the base page, or otherwise show some sort of profile or dashboard page.

e.g. github.com or dataquest.io

**Comment by sl33t** [comment]
Should the home page after login always redirect to the user dashboard?

I think so yeah but I'll go with the group if we wanna change.

I can redo the index so instead it ignores the homepage if they are logged in. Just let me know if I should.

**Comment by audiolion** [comment]
@sl33t that is what I think but yeah want to see what the group consensus is

**Comment by sl33t** [comment]
Group has decided to follow through with dashboard redirect. Homepage will no longer be accessable by user who is not logged in.
